language: java
deploy:
  provider: heroku
  api_key:
    secure: SA9EMSLD9QzeWl9Ev/S4q7LxVc62NDKHwvqIKTXMnae7eOZ/TdIflZOBOQzCh5ZljxExasf/1dp4T/pgQc4TzoSji2GRaGTB4EUy9DckWZgRZOstOsjvK5G23RN2pUHi077z0Rij5VWoAtJiocA/No+Ou+3c1xnsgefgDh4xqEMwzP4w5ZW8uFmCrKF4WGlEmWeAeWwJdtK7UrBIp+bFhKtEih8cR9SixkqtNJ+07EQfk+UgDNB6cY23tEP5CDpfatZBg24lJ+058VTPDmf/ojD9Blo3Nf6rPAUKVzxhlj07/JW/i6LqO4onj1FR/AhEanlX4AK3LMvVa2k1yPSH1nKN4jic7EAVx4hP0hTKw1qZIvHZg5PHd/5ciQDid0UFcBRAUFsu7Tul5WOJHeMQEnnXAfpQ2hB6Gxqtf/4YsyAuxLxvot2woqf7sFz5P8X+mtMojovNS4vLmCEjIUBw1TM8dVVlXFUgBRrIsafgf1hBEY4c4lmFtPtrU3/mhMrlMbnBrNLo/LQh5iQMjn6YhCPt284GoiuwpGVehL8HcXFW6o8CFqzxqHBxtQry0Dr0VxvFe4t8iflyXtGmFkYQeJAI7Bu10nljLJ3Qh+GcPmiSxpE7gaMj+FffPtuztd70yNham4QB6uNiTiIlXA94PP0C9NWspK6F4eIc2b5sRQs=
  app: intense-ridge-99027
  on:
    repo: HPrinz/asq-server
